### ISSUE TITLE
Connection Errors again

### ISSUE THREAD

**Issue by Stinky78** [Foddy/node-red-contrib-huemagic#36]
Hi there,

i have seen the already closed issues, but i still have the problems with the latest version. I am running Docker on my Synology NAS and till down everything worked absolutely nicely, at least till i have added more Hue Motion sensors. Before i had 5 lamps and one motion sensor and everything worked great. Then i have added two additional motion sensors and all went downhill. I have connection errors with the motion sensors and even with one of the lamps now. I have fiddled around with the polling interval between 1000 and 10000, but nothing seems to work. Are 3 motion sensors too much? Btw in the Hue iPhone app everything is fine and the motion sensors function properly when i have added rules in the motion app (lights on when dark and movement).

Anyone an idea?

Thank you and best regards,
S

**Comment by vBiggles** [comment]
Hi,
  

  
Have you tried putting a debug node on the motion nodes, temp and light level nodes?    I noticed that not all, but a few of my philips hue motion sensors were very "chatty" sending at least three or more messages to node-red per second.
  

  
This was maxing out the poor old raspi CPU and all my flows were slow.
  

  
I don't know the root cause of the issue, but putting a delay node on the temp and light level sensors so they could only forward 1 message per minute assisted greatly.
  

  
Of course you don't want that on your motion node though.    So if that is the node who is chatty you may need to look deeper.    Perhaps have a look at the hue API that huemagic is built on?    If you run that barebones and see what's going on there.
  

  
Hope that helps.
  

  
M
  

  
  

  
  
>

**Comment by Stinky78** [comment]
Hi there and thanks for your quick reply.

I checked that already and the temp and light sensor nodes aren't that chatty. A handful of messages a minute, at most. The motion sensor nodes do nothing till they detect motion. Then they flood the node with messages as long as it detects motion ... which is kinda the point, but its several messages a second.

Regarding performance, i am running node-red in docker with high-prio (cpu und ram) on a Synology DS918+ with 4-Core 1,5Ghz Celeron and 16GB Ram. I am more or less confident that at least the system performance isn't an issue (hopefully).

What i have seen is that even when i restart node-red the motion-nodes sometimes get connection errors, even when there is no motion. So i don't know if the motion-node-flooding is related, on the other hand, when node-red starts it fires up all the flows and has some load, so in the end it could all come together. BTW the light and temp nodes never have connection errors, at least till today (fingers crossed).

Regarding your tip with the throtteling. How would you accomplish that? Delay? Stoptimer?

Thank you and byebye,
S

**Comment by vBiggles** [comment]
In order to delay the messages, you would use the delay node.  You can rate limit messages with that, I configured it to forward the last received message every 1 minute and discard any other messages.

If you’re taking light levels, or temperature, 1min resolution is usually enough.

Regarding the connection errors, I’ve noticed that my motion detectors “wake up”.  For example, when I’m away from the house all day they seem to go to “sleep” and show up as “connection error”.  When you walk past them, it takes a few seconds longer to react, but they do detect motion, seems to take 5 seconds or so, then they stay “awake” and detect motion instantly.

I wonder if there’s a “sleep” mode in the philips hue devices to save the battery.

M

**Comment by stokni** [comment]
having the same issue, when connecting more lights (3rd - 5th) in my case, getting connection errors..  non chatty sensors here.

**Comment by vBiggles** [comment]
All, I've just updated my bridge to the latest firmware, and now the connection errors are appearing in my implementation.  I've had to cut right back to the bare minimum motion sensors only and remove the temperature and light level sensor nodes as these were hitting a rate limit, or something on the bridge.  Once I went down to about half the nodes I had before the connection errors started to go away.  It seems like a new lower command limit on the bridge itself?

**Comment by lespatots** [comment]
I think my error #38 is another manifestation of a bridge problem too. The errors almost certainly started after a firmware update. The Hue Developer site has some people reporting problems for systems that used to work and now don't. The motion sensor is one item causing problems so I shall disable mine and see what changes.

**Comment by theman00011** [comment]
Having the same problem here. Have 12 lights and 3 of them initialize and then get connection errors.

**Comment by hanssep** [comment]
Same here. 17 lights, 2 switches. Connection errors on all Huemagic nodes. Sometimes they come back online when triggered but becoming slower and increasingly unreliable.

**Comment by vBiggles** [comment]
All

I still expect this to be a new rate limit on the bridge.  I found that if I reduce the number of nodes polling the bridge that things work fine.

I think we will have to experiment with your own setups to determine what balance is best until an update to the bridge or hue magic or its components.

M


Sent from myMail for iOS


Saturday, 10 March 2018, 3:42 am +1000 from notifications@github.com  <notifications@github.com>:

**Comment by hanssep** [comment]
Seems to be related to the Hue switches? See below for the huemagic errors I captured.

`2|node-red | 13 Mar 06:59:29 - [error] [hue-switch:Hue dimmer Kitchen] Error: Huejay: read ECONNRESET
2|node-red | 13 Mar 06:59:46 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: Request failed with status code 500
2|node-red | 13 Mar 06:59:47 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: socket hang up
2|node-red | 13 Mar 06:59:49 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: read ECONNRESET
2|node-red | 13 Mar 06:59:51 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: read ECONNRESET
2|node-red | 13 Mar 06:59:52 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: Request failed with status code 500
2|node-red | 13 Mar 06:59:54 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: Request failed with status code 500
2|node-red | 13 Mar 06:59:56 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: Request failed with status code 500
2|node-red | 13 Mar 06:59:57 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: read ECONNRESET
2|node-red | 13 Mar 06:59:59 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: read ECONNRESET
2|node-red | 13 Mar 07:00:00 - [error] [hue-switch:Hue dimmer master bedroom] Error: Huejay: read ECONNRESET
2|node-red | 13 Mar 07:00:00 - [error] [hue-switch:Hue dimmer Kitchen] Error: Huejay: read ECONNRESET`

Detailed error here:

`failed to parse respose from http://192.168.0.215:80/description.xml
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

Error: Unexpected close tag
Line: 5
Column: 7
Char: >
    at error (/root/.node-red/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/root/.node-red/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/root/.node-red/node_modules/sax/lib/sax.js:871:9)
    at SAXParser.write (/root/.node-red/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/root/.node-red/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/root/.node-red/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/root/.node-red/node_modules/xml2js/lib/parser.js:354:19)
    at Request._callback (/root/.node-red/node_modules/node-red-node-wemo/lib/wemo.js:125:16)
    at Request.self.callback (/root/.node-red/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/.node-red/node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/.node-red/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Failed to GET info from http://192.168.0.215:80/description.xml
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

**Comment by hanssep** [comment]
@theman00011 How do you add additional users? Via the Hue API?

**Comment by Tandriin** [comment]
YFI: I've an openHAB Instance running with the Hue Binding. The binding is using the api without problems.
I'm not that good in coding to find the differences. But maybe that helps if somebody who can code compares the code who querys the hue bridge api

**Comment by ozdeadmeat** [comment]
I will give the multiple user thing a go tonight and report back. Might be a way to mitigate the performance degradation for flows with large numbers of hue entities.

**Comment by ozdeadmeat** [comment]
The Bridge needed to be restarted, things seem stable with only 1 or 2 errors a day now. Not sure how reliable Huejay is when it comes to increasing the count of lights to over 50 and more than 20 sensors. That is my end state and frankly I am not even 50% of the way there and seeing performance issues. I wonder if it will be better when the zigbee 3.0 update comes out for the hue bridge.

**Comment by K-RAD** [comment]
Any news on this? I have only like 14 lights set up (no scenes, no switch/tap yet) and even when they're all off I see a bunch of "Error: Huejay: read ECONNRESET"

**Comment by filoor** [comment]
I'm facing the same problem 
"Error: Huejay: socket hang up"

**Comment by jarlave** [comment]
Got that error now too after adding a few more bulbs.
Maybe it would help to make a global context (like the home assistant node does) and update this every few seconds so the other nodes take the current state from this global context instead of polling the bridge separately?

**Comment by jamieshaw** [comment]
👆🏻 Agreed. Global context would be much more useful; I'm polling 10 or so switches (seemingly at the same moment) and it's just flooding the bridge with requests.

**Comment by lespatots** [comment]
Without knowing more about your setup I'm maybe wrong but there is a theoretical limit of seven switches on each hue bridge as each switch apparantly now takes up 13 rules each from the 100 available? For that reason I have two bridges and I'm contemplating a third as I plan to use switches as Homekit input devices rather than only for Hue bulbs.

Of course multi-bridges makes Hue only setups very difficult as splitting lights/switches acrosss bridges causes logistic issues.

**Comment by jamieshaw** [comment]
No multi bridge here – although, I lied, the actual count is 8 dimmer switches not 10. I don't have issues outside of the contrib node.

**Comment by lespatots** [comment]
If the bridge was full apparantly it won't let you add more. Looking further I note that perhaps Philips increased the rule limit to 200 but be wary of the slow down. I also read that if you use a different app a switch may not tie up so many rules, so more research might temporarily provide a solution?

**Comment by stainlessray** [comment]
I own nine bulbs. This issue has existed since I started using these nodes. The issue has been closed without resolution before. What is going on? How can one expect to use a platform in this state? And before anyone decides to lecture me on contributing to the solution, my errors are already cited by several others. I want to know what the dev is doing about it to decide if HA is no longer a viable option for my lights.

**Comment by stainlessray** [comment]
> The Bridge needed to be restarted, things seem stable with only 1 or 2 errors a day now. Not sure how reliable Huejay is when it comes to increasing the count of lights to over 50 and more than 20 sensors. That is my end state and frankly I am not even 50% of the way there and seeing performance issues. I wonder if it will be better when the zigbee 3.0 update comes out for the hue bridge.

I have 9 bulbs. 9 nodes. this error torpedoes my flows.

**Comment by danrspencer** [comment]
> I own nine bulbs. This issue has existed since I started using these nodes. The issue has been closed without resolution before. What is going on? How can one expect to use a platform in this state? And before anyone decides to lecture me on contributing to the solution, my errors are already cited by several others. I want to know what the dev is doing about it to decide if HA is no longer a viable option for my lights.

If you're running NodeRED on top of Home Assistant I suggest you just use the new [HA Websocket Contrib](https://github.com/zachowj/node-red-contrib-home-assistant-websocket). If you're using Hassio the NR addon was updated today to use the websocket contrib as the default. 

You can then let HA manage your lights and the websocket connection between NR and HA ensures everything is very fast. I moved to it a few weeks ago and everything has been substantially better / faster since and I no longer feel the need for a separate Hue contrib (just as well since it looks like this project is dead).

**Comment by jarlave** [comment]
I did this too after my comment here, just let home assistant manage your lights and use the websocket contrib, works perfectly

**Comment by stainlessray** [comment]
Thanks for the replies. I will look into the websocket. +10 points for the community.

**Comment by jamieshaw** [comment]
The HA websocket is great for Home Assistant stuff; but doesn't include features such as sensor, switch and dimmer polling.  I also find that Hue Magic's scene triggering/discovery is much more reliable that the `activate_hue_scene` service used by Home Assistant.

**Comment by Foddy** [comment]
Fixed with v1.7.0

**Comment by ThomasPoett** [comment]
Out off the blue, this started a couple of days with the newst version 2.0.x again.
I wasn't able fixing the light with this error.
a work around was: instead of a light node, i used a groups node. 

but still having the issue, that i have nill and nothing response from any switch/motion sensor. and they are on a dedicate 2nd bridge.
